
package com.banguat.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TipoCambioSoap", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TipoCambioSoap {


    /**
     * Despliega las variables (con relación a la moneda) disponibles para consulta.
     * 
     * @return
     *     returns com.banguat.soap.InfoVariable
     */
    @WebMethod(operationName = "VariablesDisponibles", action = "http://www.banguat.gob.gt/variables/ws/VariablesDisponibles")
    @WebResult(name = "VariablesDisponiblesResult", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
    @RequestWrapper(localName = "VariablesDisponibles", targetNamespace = "http://www.banguat.gob.gt/variables/ws/", className = "com.banguat.soap.VariablesDisponibles")
    @ResponseWrapper(localName = "VariablesDisponiblesResponse", targetNamespace = "http://www.banguat.gob.gt/variables/ws/", className = "com.banguat.soap.VariablesDisponiblesResponse")
    public InfoVariable variablesDisponibles();

    /**
     * Despliega el tipo de cambio correspondiente a una variable (moneda) dada. (Formato: moneda=2) 
     * 
     * @param variable
     * @return
     *     returns com.banguat.soap.InfoVariable
     */
    @WebMethod(operationName = "Variables", action = "http://www.banguat.gob.gt/variables/ws/Variables")
    @WebResult(name = "VariablesResult", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
    @RequestWrapper(localName = "Variables", targetNamespace = "http://www.banguat.gob.gt/variables/ws/", className = "com.banguat.soap.Variables")
    @ResponseWrapper(localName = "VariablesResponse", targetNamespace = "http://www.banguat.gob.gt/variables/ws/", className = "com.banguat.soap.VariablesResponse")
    public InfoVariable variables(
        @WebParam(name = "variable", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
        int variable);

    /**
     * Despliega la información del tipo de cambio, en dólares, desde una fecha dada hasta el día corriente. (Formato: fecha_ini=dd/mm/aaaa).
     * 
     * @param fechainit
     * @return
     *     returns com.banguat.soap.DataVariable
     */
    @WebMethod(operationName = "TipoCambioFechaInicial", action = "http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicial")
    @WebResult(name = "TipoCambioFechaInicialResult", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
    @RequestWrapper(localName = "TipoCambioFechaInicial", targetNamespace = "http://www.banguat.gob.gt/variables/ws/", className = "com.banguat.soap.TipoCambioFechaInicial")
    @ResponseWrapper(localName = "TipoCambioFechaInicialResponse", targetNamespace = "http://www.banguat.gob.gt/variables/ws/", className = "com.banguat.soap.TipoCambioFechaInicialResponse")
    public DataVariable tipoCambioFechaInicial(
        @WebParam(name = "fechainit", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
        String fechainit);

    /**
     * Despliega la información para dólares en el período de tiempo dado. (Formato: fecha_ini=dd/mm/aaaa fecha_fin=dd/mm/aaaa)
     * 
     * @param fechainit
     * @param fechafin
     * @return
     *     returns com.banguat.soap.DataVariable
     */
    @WebMethod(operationName = "TipoCambioRango", action = "http://www.banguat.gob.gt/variables/ws/TipoCambioRango")
    @WebResult(name = "TipoCambioRangoResult", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
    @RequestWrapper(localName = "TipoCambioRango", targetNamespace = "http://www.banguat.gob.gt/variables/ws/", className = "com.banguat.soap.TipoCambioRango")
    @ResponseWrapper(localName = "TipoCambioRangoResponse", targetNamespace = "http://www.banguat.gob.gt/variables/ws/", className = "com.banguat.soap.TipoCambioRangoResponse")
    public DataVariable tipoCambioRango(
        @WebParam(name = "fechainit", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
        String fechainit,
        @WebParam(name = "fechafin", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
        String fechafin);

    /**
     * Despliega la información para la variable indicada a partir de una fecha y moneda indicada. (Formato: fecha_ini=dd/mm/aaaa moneda=02).
     * 
     * @param fechainit
     * @param moneda
     * @return
     *     returns com.banguat.soap.DataVariable
     */
    @WebMethod(operationName = "TipoCambioFechaInicialMoneda", action = "http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicialMoneda")
    @WebResult(name = "TipoCambioFechaInicialMonedaResult", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
    @RequestWrapper(localName = "TipoCambioFechaInicialMoneda", targetNamespace = "http://www.banguat.gob.gt/variables/ws/", className = "com.banguat.soap.TipoCambioFechaInicialMoneda")
    @ResponseWrapper(localName = "TipoCambioFechaInicialMonedaResponse", targetNamespace = "http://www.banguat.gob.gt/variables/ws/", className = "com.banguat.soap.TipoCambioFechaInicialMonedaResponse")
    public DataVariable tipoCambioFechaInicialMoneda(
        @WebParam(name = "fechainit", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
        String fechainit,
        @WebParam(name = "moneda", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
        int moneda);

    /**
     * Despliega la información para la variable indicada en el período de tiempo y la moneda dada. (Formato: fecha_ini=dd/mm/aaaa fecha_fin=dd/mm/aaaa moneda=02)
     * 
     * @param fechainit
     * @param moneda
     * @param fechafin
     * @return
     *     returns com.banguat.soap.DataVariable
     */
    @WebMethod(operationName = "TipoCambioRangoMoneda", action = "http://www.banguat.gob.gt/variables/ws/TipoCambioRangoMoneda")
    @WebResult(name = "TipoCambioRangoMonedaResult", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
    @RequestWrapper(localName = "TipoCambioRangoMoneda", targetNamespace = "http://www.banguat.gob.gt/variables/ws/", className = "com.banguat.soap.TipoCambioRangoMoneda")
    @ResponseWrapper(localName = "TipoCambioRangoMonedaResponse", targetNamespace = "http://www.banguat.gob.gt/variables/ws/", className = "com.banguat.soap.TipoCambioRangoMonedaResponse")
    public DataVariable tipoCambioRangoMoneda(
        @WebParam(name = "fechainit", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
        String fechainit,
        @WebParam(name = "fechafin", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
        String fechafin,
        @WebParam(name = "moneda", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
        int moneda);

    /**
     * Devuelve el cambio del día en dólares
     * 
     * @return
     *     returns com.banguat.soap.InfoVariable
     */
    @WebMethod(operationName = "TipoCambioDia", action = "http://www.banguat.gob.gt/variables/ws/TipoCambioDia")
    @WebResult(name = "TipoCambioDiaResult", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
    @RequestWrapper(localName = "TipoCambioDia", targetNamespace = "http://www.banguat.gob.gt/variables/ws/", className = "com.banguat.soap.TipoCambioDia")
    @ResponseWrapper(localName = "TipoCambioDiaResponse", targetNamespace = "http://www.banguat.gob.gt/variables/ws/", className = "com.banguat.soap.TipoCambioDiaResponse")
    public InfoVariable tipoCambioDia();

    /**
     * Devuelve el cambio del día en dólares
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TipoCambioDiaString", action = "http://www.banguat.gob.gt/variables/ws/TipoCambioDiaString")
    @WebResult(name = "TipoCambioDiaStringResult", targetNamespace = "http://www.banguat.gob.gt/variables/ws/")
    @RequestWrapper(localName = "TipoCambioDiaString", targetNamespace = "http://www.banguat.gob.gt/variables/ws/", className = "com.banguat.soap.TipoCambioDiaString")
    @ResponseWrapper(localName = "TipoCambioDiaStringResponse", targetNamespace = "http://www.banguat.gob.gt/variables/ws/", className = "com.banguat.soap.TipoCambioDiaStringResponse")
    public String tipoCambioDiaString();

}
